export type Character = {
  name: string;
  image: string;
  detailImage?: string;
  imageAspectRatio?: string;
  imagePosition?: string;
  detailImagePosition?: string;
  description: string;
  role: string;
  type: string;
  typeImage?: string;
  englishVoiceActor?: string;
  japaneseVoiceActor?: string;
  region?: string;
  regionImage?: string;
  releaseDate?: string;
  birthday?: string;
  weapon?: string;
  weaponName?: string;
  weaponImage?: string;
  buildLabel?: string;
  buildName?: string;
  buildImage?: string;
  skillName?: string;
  skillType?: "Active" | "Passive";
  skillDescription?: string;
};

export type Game = {
  slug: string;
  name: string;
  imgSrc: string;
  bannerSrc: string;
  uid: string;
  favoriteCharacter: string;
  favoriteCharacterDescription: string;
  about: string;
  status: string;
  tagline: string;
  characters: Character[];
};

export const gameData: Game[] = [
  {
    slug: "genshin-impact",
    name: "Genshin Impact",
    imgSrc: "/Genshin_Impact.webp",
    bannerSrc: "/Genshin_Impact.webp",
    uid: "Asia 8234 11822",
    favoriteCharacter: "Raiden Shogun",
    favoriteCharacterDescription: "My go-to carry for polished electro teams, clean burst windows, and that unmistakable Inazuma presence.",
    about: "My long-term exploration account with polished builds, event clears, and a lot of late-night artifact farming.",
    status: "Adventure Rank 60",
    tagline: "Exploration, events, and min-maxed comfort rotations.",
    characters: [
      {
        name: "Raiden Shogun",
        image: "/picked-characters-and-wepaons/raiden-shogun-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/raiden-shogun-pic.jpg",
        imagePosition: "center 20%",
        detailImagePosition: "center 14%",
        description: "Electro Archon of Inazuma and still one of the cleanest burst carries to build a polished account around.",
        weapon: "Polearm",
        weaponName: "Engulfing Lightning",
        role: "Burst DPS",
        type: "Electro",
        englishVoiceActor: "Anne Yatco",
        japaneseVoiceActor: "Sawashiro Miyuki",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "September 1, 2021",
        birthday: "June 26",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Engulfing_Lightning-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Emblem of Severed Fate",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Yelan",
        image: "/picked-characters-and-wepaons/yelan-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/yelan-pic.jpg",
        description: "A flexible hydro sub-DPS who fits into fast rotations and keeps teams feeling smooth and reliable.",
        weapon: "Bow",
        weaponName: "Aqua Simulacra",
        role: "Sub DPS",
        type: "Hydro",
        englishVoiceActor: "Laura Post",
        japaneseVoiceActor: "Endou Aya",
        region: "Liyue",
        regionImage: "/genshin-region/Liyue_Emblem_Night.webp",
        releaseDate: "May 31, 2022",
        birthday: "April 20",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Aqua_Simulacra-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Emblem of Severed Fate",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Yoimiya",
        image: "/picked-characters-and-wepaons/yoimiya-pic.webp",
        detailImage: "/picked-characters-and-wepaons/yoimiya-pic.webp",
        description: "A comfortable pyro carry for single-target fights with bright visuals and very straightforward gameplay.",
        weapon: "Bow",
        weaponName: "Thundering Pulse",
        role: "Main DPS",
        type: "Pyro",
        englishVoiceActor: "Jenny Yokobori",
        japaneseVoiceActor: "Ueda Kana",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "August 10, 2021",
        birthday: "June 21",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Thundering_Pulse-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Shimenawa's Reminiscence",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Kamisato Ayaka",
        image: "/picked-characters-and-wepaons/kamisato-ayaka-pic.avif",
        detailImage: "/picked-characters-and-wepaons/kamisato-ayaka-pic.avif",
        description: "A premium cryo sword carry known for elegant freeze teams and consistent burst damage.",
        weapon: "Sword",
        weaponName: "Mistsplitter Reforged",
        role: "Main DPS",
        type: "Cryo",
        englishVoiceActor: "Erica Mendez",
        japaneseVoiceActor: "Hayami Saori",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "July 21, 2021",
        birthday: "September 28",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Mistsplitter_Reforged-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Blizzard Strayer",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Sangonomiya Kokomi",
        image: "/picked-characters-and-wepaons/sangonomiya-kokomi-pic.webp",
        detailImage: "/picked-characters-and-wepaons/sangonomiya-kokomi-pic.webp",
        description: "A strong hydro support with dependable healing and comfortable utility for freeze or bloom teams.",
        weapon: "Catalyst",
        weaponName: "Everlasting Moonglow",
        role: "Healer",
        type: "Hydro",
        englishVoiceActor: "Risa Mei",
        japaneseVoiceActor: "Mimori Suzuko",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "September 21, 2021",
        birthday: "February 22",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Everlasting_Moonglow-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Ocean-Hued Clam",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Shenhe",
        image: "/picked-characters-and-wepaons/shenhe-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/shenhe-pic.jpg",
        description: "A dedicated cryo buffer who makes premium cryo teams hit much harder with very clean support value.",
        weapon: "Polearm",
        weaponName: "Calamity Queller",
        role: "Support",
        type: "Cryo",
        englishVoiceActor: "Chelsea Kwoka",
        japaneseVoiceActor: "Kawasumi Ayako",
        region: "Liyue",
        regionImage: "/genshin-region/Liyue_Emblem_Night.webp",
        releaseDate: "January 5, 2022",
        birthday: "March 10",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Calamity_Queller-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Noblesse Oblige",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Skirk",
        image: "/picked-characters-and-wepaons/skirk-pic.avif",
        detailImage: "/picked-characters-and-wepaons/skirk-pic.avif",
        imagePosition: "center 12%",
        detailImagePosition: "center 10%",
        description: "A highly anticipated swordswoman with a mysterious style that already feels iconic in the game's lore.",
        weapon: "Sword",
        weaponName: "Azurelight",
        role: "Hypercarry",
        type: "Cryo",
        englishVoiceActor: "Cat Protano",
        japaneseVoiceActor: "Noto Mamiko",
        region: "Unknown",
        regionImage: "/genshin-region/Emblem_Nation_Unknown.webp",
        releaseDate: "June 18, 2025",
        birthday: "November 5",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Azurelight-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Gladiator's Finale",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Arlecchino",
        image: "/picked-characters-and-wepaons/arlecchino-pic.avif",
        detailImage: "/picked-characters-and-wepaons/arlecchino-pic.avif",
        description: "An aggressive pyro polearm carry with a stylish combat loop and a very strong account presence.",
        weapon: "Polearm",
        weaponName: "Crimson Moon's Semblance",
        role: "Main DPS",
        type: "Pyro",
        englishVoiceActor: "Erin Yvette",
        japaneseVoiceActor: "Mori Nanako",
        region: "Khaenri'ah",
        regionImage: "/genshin-region/khaenri'ah-region.webp",
        releaseDate: "April 24, 2024",
        birthday: "August 22",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Crimson_Moons_Semblance-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Fragment of Harmonic Whimsy",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Chiori",
        image: "/picked-characters-and-wepaons/chiori-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/chiori-pic.jpg",
        description: "A geo sword unit with elegant style and solid off-field pressure for geo-centered teams.",
        weapon: "Sword",
        weaponName: "Uraku Misugiri",
        role: "Sub DPS",
        type: "Geo",
        englishVoiceActor: "Brittany Lauda",
        japaneseVoiceActor: "Taketatsu Ayana",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "March 13, 2024",
        birthday: "August 17",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Uraku_Misugiri-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Golden Troupe",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Columbina",
        image: "/picked-characters-and-wepaons/columbina-pic.avif",
        detailImage: "/picked-characters-and-wepaons/columbina-pic.avif",
        description: "One of the most intriguing Harbingers, included here as a lore-driven favorite with huge future potential.",
        weapon: "Catalyst",
        weaponName: "Nocturne's Curtain Call",
        role: "Unknown",
        type: "Hydro",
        englishVoiceActor: "Emi Lo",
        japaneseVoiceActor: "Lynn",
        region: "Nod-Krai",
        regionImage: "/genshin-region/Nod-Krai_Emblem_Night.webp",
        releaseDate: "January 14, 2026",
        birthday: "January 14",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Nocturnes_Curtain_Call-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Future Build",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Kaedehara Kazuha",
        image: "/picked-characters-and-wepaons/kaedehara-kazuha-pic.png",
        detailImage: "/picked-characters-and-wepaons/kaedehara-kazuha-pic.png",
        description: "A top-tier anemo support for grouping, resistance shred, and making almost any team feel smoother.",
        weapon: "Sword",
        weaponName: "Freedom-Sworn",
        role: "Support",
        type: "Anemo",
        englishVoiceActor: "Mark Whitten",
        japaneseVoiceActor: "Shimazaki Nobunaga",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "June 29, 2021",
        birthday: "October 29",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Freedom_Sworn-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Viridescent Venerer",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Kujou Sara",
        image: "/picked-characters-and-wepaons/kujou-sara-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/kujou-sara-pic.jpg",
        description: "A niche but stylish electro support that still feels great when paired with burst-focused carries.",
        weapon: "Bow",
        weaponName: "Mouun's Moon",
        role: "Buffer",
        type: "Electro",
        englishVoiceActor: "Jeannie Tirado",
        japaneseVoiceActor: "Seto Asami",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "September 1, 2021",
        birthday: "July 14",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Mouuns_Moon-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Emblem of Severed Fate",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Mavuika",
        image: "/picked-characters-and-wepaons/mavuika-pic.avif",
        detailImage: "/picked-characters-and-wepaons/mavuika-pic.avif",
        description: "Natlan's pyro archon energy gives her instant standout value as a future-focused favorite.",
        weapon: "Claymore",
        weaponName: "A Thousand Blazing Suns",
        role: "Main DPS",
        type: "Pyro",
        englishVoiceActor: "Katiana Sarkissian",
        japaneseVoiceActor: "Komatsu Mikako",
        region: "Natlan",
        regionImage: "/genshin-region/Natlan_Emblem_Night.webp",
        releaseDate: "January 1, 2025",
        birthday: "August 28",
        weaponImage: "/picked-characters-and-wepaons/Weapon_A_Thousand_Blazing_Suns-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Marechaussee Hunter",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Nilou",
        image: "/picked-characters-and-wepaons/nilou-pic.webp",
        detailImage: "/picked-characters-and-wepaons/nilou-pic.webp",
        description: "A bloom-focused hydro dancer whose teams feel unique, clean, and very satisfying when built correctly.",
        weapon: "Sword",
        weaponName: "Key of Khaj-Nisut",
        role: "Enabler",
        type: "Hydro",
        englishVoiceActor: "Dani Chambers",
        japaneseVoiceActor: "Kanemoto Hisako",
        region: "Sumeru",
        regionImage: "/genshin-region/Sumeru_Emblem_Night.webp",
        releaseDate: "October 14, 2022",
        birthday: "December 3",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Key_of_Khaj_Nisut-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Vourukasha's Glow",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Ningguang",
        image: "/picked-characters-and-wepaons/ningguang-pic.webp",
        detailImage: "/picked-characters-and-wepaons/ningguang-pic.webp",
        description: "A classic geo catalyst unit with strong style and that unmistakable Liyue elite vibe.",
        weapon: "Catalyst",
        weaponName: "Lost Prayer to the Sacred Winds",
        role: "Main DPS",
        type: "Geo",
        englishVoiceActor: "Erin Ebers",
        japaneseVoiceActor: "Ohara Sayaka",
        region: "Liyue",
        regionImage: "/genshin-region/Liyue_Emblem_Night.webp",
        releaseDate: "September 28, 2020",
        birthday: "August 26",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Lost_Prayer_to_the_Sacred_Winds-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Archaic Petra",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Venti",
        image: "/picked-characters-and-wepaons/venti-pic.avif",
        detailImage: "/picked-characters-and-wepaons/venti-pic.avif",
        description: "A legendary crowd-control support who still makes many fights feel effortless and stylish.",
        weapon: "Bow",
        weaponName: "The Daybreak Chronicles",
        role: "Support",
        type: "Anemo",
        englishVoiceActor: "Erika Harlacher",
        japaneseVoiceActor: "Murase Ayumu",
        region: "Mondstadt",
        regionImage: "/genshin-region/Mondstadt_Emblem_Night.webp",
        releaseDate: "September 28, 2020",
        birthday: "June 16",
        weaponImage: "/picked-characters-and-wepaons/Weapon_The_Daybreak_Chronicles-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Viridescent Venerer",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Wanderer",
        image: "/picked-characters-and-wepaons/wanderer-pic.png",
        detailImage: "/picked-characters-and-wepaons/wanderer-pic.png",
        description: "A fast and expressive anemo hypercarry with excellent movement and standout visual identity.",
        weapon: "Catalyst",
        weaponName: "Tulaytullah's Remembrance",
        role: "Hypercarry",
        type: "Anemo",
        englishVoiceActor: "Patrick Pedraza",
        japaneseVoiceActor: "Kakihara Tetsuya",
        region: "Sumeru",
        regionImage: "/genshin-region/Sumeru_Emblem_Night.webp",
        releaseDate: "December 7, 2022",
        birthday: "January 3",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Tulaytullahs_Remembrance-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Desert Pavilion Chronicle",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Yae Miko",
        image: "/picked-characters-and-wepaons/yaemiko-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/yaemiko-pic.jpg",
        description: "An elegant off-field electro unit with great style, totem pressure, and strong account value.",
        weapon: "Catalyst",
        weaponName: "Kagura's Verity",
        role: "Sub DPS",
        type: "Electro",
        englishVoiceActor: "Ratana",
        japaneseVoiceActor: "Sakura Ayane",
        region: "Inazuma",
        regionImage: "/genshin-region/Inazuma_Emblem_Night.webp",
        releaseDate: "February 16, 2022",
        birthday: "June 27",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Kaguras_Verity-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Golden Troupe",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Zibai",
        image: "/picked-characters-and-wepaons/zibai-pic.avif",
        detailImage: "/picked-characters-and-wepaons/zibai-pic.avif",
        description: "Included as one of your requested picks, kept here as an unreleased or speculative favorite entry.",
        weapon: "Sword",
        weaponName: "Lightbearing Moonshard",
        role: "Unknown",
        type: "Geo",
        englishVoiceActor: "Laura Welsh",
        japaneseVoiceActor: "Fukuen Misato",
        region: "Liyue",
        regionImage: "/genshin-region/Liyue_Emblem_Night.webp",
        releaseDate: "February 3, 2026",
        birthday: "May 15",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Lightbearing_Moonshard-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Future Build",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Zhongli",
        image: "/picked-characters-and-wepaons/zongli-pic.avif",
        detailImage: "/picked-characters-and-wepaons/zongli-pic.avif",
        description: "Still one of the most comfortable supports in the game thanks to his shield, utility, and universal value.",
        weapon: "Polearm",
        weaponName: "Vortex Vanquisher",
        role: "Shielder",
        type: "Geo",
        englishVoiceActor: "Keith Silverstein",
        japaneseVoiceActor: "Maeno Tomoaki",
        region: "Liyue",
        regionImage: "/genshin-region/Liyue_Emblem_Night.webp",
        releaseDate: "December 1, 2020",
        birthday: "December 31",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Vortex_Vanquisher-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Tenacity of the Millelith",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Eula",
        image: "/picked-characters-and-wepaons/eula-pic.avif",
        detailImage: "/picked-characters-and-wepaons/eula-pic.avif",
        description: "A physical burst carry with one of the most satisfying nuke windows in the game.",
        weapon: "Claymore",
        weaponName: "Song of Broken Pines",
        role: "Main DPS",
        type: "Cryo",
        englishVoiceActor: "Suzie Yeung",
        japaneseVoiceActor: "Satou Rina",
        region: "Mondstadt",
        regionImage: "/genshin-region/Mondstadt_Emblem_Night.webp",
        releaseDate: "November 24, 2021",
        birthday: "October 25",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Song_of_Broken_Pines-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Pale Flame",
        buildImage: "/artifact-core.svg",
      },
      {
        name: "Aloy",
        image: "/picked-characters-and-wepaons/aloy-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/aloy-pic.jpg",
        description: "A crossover cryo bow character who still stands out as a unique collector pick in the roster.",
        weapon: "Bow",
        weaponName: "Predator",
        role: "Burst DPS",
        type: "Cryo",
        englishVoiceActor: "Giselle Fernandez",
        japaneseVoiceActor: "Takagaki Ayahi",
        region: "Unknown",
        regionImage: "/genshin-region/Emblem_Nation_Unknown.webp",
        releaseDate: "September 1, 2021",
        birthday: "April 4",
        weaponImage: "/picked-characters-and-wepaons/aloy-wepon-cutout.png",
        buildLabel: "Artifact Set",
        buildName: "Blizzard Strayer",
        buildImage: "/artifact-core.svg",
      },
    ],
  },
  {
    slug: "star-rail",
    name: "Star Rail",
    imgSrc: "/side-bar/Star-Rail.png",
    bannerSrc: "/side-bar/Star-Rail.png",
    uid: "NA 6017 44291",
    favoriteCharacter: "Acheron",
    favoriteCharacterDescription: "The account centerpiece for high-impact runs, clean ult-focused pacing, and that unmistakable Star Rail presence.",
    about: "Focused on polished hypercarry and support lineups, Memory of Chaos pushes, and a roster built around premium showcase characters.",
    status: "Trailblaze Level 70",
    tagline: "Showcase clears with a premium HSR roster.",
    characters: [
      {
        name: "Acheron",
        image: "/picked-characters-and-wepaons/acheron-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/acheron-hsr-pic.webp",
        description: "A premium lightning hypercarry built for high-impact clears and some of the strongest showcase damage on the account.",
        weapon: "Lightning",
        weaponName: "Along the Passing Shore",
        role: "Hypercarry",
        type: "Nihility",
        englishVoiceActor: "Allegra Clark",
        japaneseVoiceActor: "Sawashiro Miyuki",
        weaponImage: "/picked-characters-and-wepaons/acheron-wep-hsr.jpg",
      },
      {
        name: "Feixiao",
        image: "/picked-characters-and-wepaons/feixiao-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/feixiao-hsr-pic.webp",
        description: "A fast hunt carry with clean burst pressure and the kind of sharp visual identity that anchors the whole page.",
        weapon: "Wind",
        weaponName: "I Venture Forth to Hunt",
        role: "Main DPS",
        type: "The Hunt",
        englishVoiceActor: "Anairis Quiñones",
        japaneseVoiceActor: "Komatsu Mikako",
        weaponImage: "/picked-characters-and-wepaons/feixian-wep-hsr.webp",
      },
      {
        name: "Sparkle",
        image: "/picked-characters-and-wepaons/sparkle-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/sparkle-hsr-pic.webp",
        description: "A top-tier quantum support that keeps premium teams smooth, explosive, and easy to pilot.",
        weapon: "Quantum",
        role: "Support",
        type: "Harmony",
        englishVoiceActor: "Lizzie Freeman",
        japaneseVoiceActor: "Ueda Reina",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Rappa",
        image: "/picked-characters-and-wepaons/rappa-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/rappa-hsr-pic.webp",
        description: "A flashy imaginary damage dealer with a distinctive style and a strong place in your Star Rail lineup.",
        weapon: "Imaginary",
        role: "Damage Dealer",
        type: "Erudition",
        englishVoiceActor: "Kendell Byrd",
        japaneseVoiceActor: "Han Megumi",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Saber",
        image: "/picked-characters-and-wepaons/saber-hsr-pic.avif",
        detailImage: "/picked-characters-and-wepaons/saber-hsr-pic.avif",
        description: "A standout crossover-style pick with strong visual presence and clear main-carry energy for the page.",
        weapon: "Wind",
        role: "Main DPS",
        type: "Destruction",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Kawasumi Ayako",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Kafka",
        image: "/picked-characters-and-wepaons/kafka-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/kafka-hsr-pic.webp",
        description: "A defining Nihility pick for stylish damage-over-time teams and that unmistakable Star Rail mood.",
        weapon: "Lightning",
        role: "Damage Dealer",
        type: "Nihility",
        englishVoiceActor: "Cheryl Texiera",
        japaneseVoiceActor: "Ito Shizuka",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Castorice",
        image: "/picked-characters-and-wepaons/castorice-hsr-pic.avif",
        detailImage: "/picked-characters-and-wepaons/castorice-hsr-pic.avif",
        description: "A standout new addition with a strong visual identity and clear premium-carry presence for the Star Rail roster.",
        weapon: "Quantum",
        role: "Damage Dealer",
        type: "Remembrance",
        englishVoiceActor: "Melody Muze",
        japaneseVoiceActor: "Saito Chiwa",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Cipher",
        image: "/picked-characters-and-wepaons/cipher-hsr-pic.avif",
        detailImage: "/picked-characters-and-wepaons/cipher-hsr-pic.avif",
        description: "A sleek support-style pick that adds more variety and a sharper sci-fi look to the Star Rail page.",
        weapon: "Quantum",
        role: "Support",
        type: "Nihility",
        englishVoiceActor: "Shea Fairaday",
        japaneseVoiceActor: "Ito Ayasa",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Evernight",
        image: "/picked-characters-and-wepaons/evernight-hsr-pic.webp",
        detailImage: "/picked-characters-and-wepaons/evernight-hsr-pic.webp",
        description: "Added from your latest HSR assets as another premium-style roster entry with a strong visual fit for the page.",
        weapon: "Imaginary",
        role: "Damage Dealer",
        type: "Erudition",
        englishVoiceActor: "Skyler Davenport",
        japaneseVoiceActor: "Ogura Yui",
        weaponImage: "/weapon-core.svg",
      },
    ],
  },
  {
    slug: "wuthering-waves",
    name: "Wuthering Waves",
    imgSrc: "/side-bar/wuwa.webp",
    bannerSrc: "/side-bar/wuwa.webp",
    uid: "SEA 9003 14852",
    favoriteCharacter: "Jinhsi",
    favoriteCharacterDescription: "A favorite for cinematic burst damage, elegant design language, and fast-paced team execution.",
    about: "Built around fast combat rotations, resonance tuning, and collecting cinematic character showcases.",
    status: "Union Level 63",
    tagline: "Fast combat loops and clean resonance builds.",
    characters: [
      {
        name: "Jinhsi",
        image: "/picked-characters-and-wepaons/jinshi-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/jinshi-wuwa-pic.jpg",
        description: "My main showcase unit with strong burst identity and polished visual combat flow.",
        weapon: "Broadblade",
        weaponName: "Ages of Harvest",
        role: "Main DPS",
        type: "Spectro",
        englishVoiceActor: "Anna Devlin",
        japaneseVoiceActor: "Aoyama Yoshino",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Ages_of_Harvest_jinshi.webp",
        buildLabel: "Echo Set",
        buildName: "Celestial Light",
        buildImage: "/echo-core.svg",
      },
      {
        name: "Changli",
        image: "/picked-characters-and-wepaons/changli-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/changli-wuwa-pic.jpg",
        description: "A stylish fusion pick that keeps the account feeling fast and expressive.",
        weapon: "Sword",
        weaponName: "Blazing Brilliance",
        role: "Sub DPS",
        type: "Fusion",
        englishVoiceActor: "Ashleigh Haddad",
        japaneseVoiceActor: "Saito Chiwa",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Blazing_Brilliance_changli.jpeg",
        buildLabel: "Echo Set",
        buildName: "Molten Rift",
        buildImage: "/echo-core.svg",
      },
      {
        name: "Camellya",
        image: "/picked-characters-and-wepaons/camellya-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/camellya-wuwa-pic.jpg",
        description: "A fast and stylish havoc carry with a strong visual identity and a sharp fit for the Wuwa showcase lineup.",
        weapon: "Sword",
        weaponName: "Red Spring",
        role: "Main DPS",
        type: "Havoc",
        englishVoiceActor: "Meaghan Martin",
        japaneseVoiceActor: "Ise Mariya",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Red_Spring_camellya.jpeg",
        buildLabel: "Echo Set",
        buildName: "Sun-sinking Eclipse",
        buildImage: "/echo-core.svg",
      },
      {
        name: "Shorekeeper",
        image: "/picked-characters-and-wepaons/shorekeeper-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/shorekeeper-wuwa-pic.jpg",
        description: "A premium support pick for smoother team flow, strong utility, and some of the cleanest Wuwa presentation on the page.",
        weapon: "Rectifier",
        weaponName: "Stellar Symphony",
        role: "Support",
        type: "Spectro",
        englishVoiceActor: "Stephanie McKeon",
        japaneseVoiceActor: "Suwa Ayaka",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Stellar_Symphony_shorekeeper.jpeg",
        buildLabel: "Echo Set",
        buildName: "Rejuvenating Glow",
        buildImage: "/echo-core.svg",
      },
      {
        name: "Aemeath",
        image: "/picked-characters-and-wepaons/aemeath-wuwa-pic.webp",
        detailImage: "/picked-characters-and-wepaons/aemeath-wuwa-pic.webp",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Unknown",
        weaponName: "Everbright Polestar",
        role: "Showcase Pick",
        type: "Fusion",
        englishVoiceActor: "Cara Theobold",
        japaneseVoiceActor: "Sato Satomi",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Everbright_Polestar_aemeath.jpeg",
      },
      {
        name: "Augusta",
        image: "/picked-characters-and-wepaons/augusta-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/augusta-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Broadblade",
        weaponName: "Thunderflare Dominion",
        role: "Showcase Pick",
        type: "Electro",
        englishVoiceActor: "Alix Wilton Regan",
        japaneseVoiceActor: "Hikasa Yoko",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Thunderflare_Dominion.jpeg",
      },
      {
        name: "Carlotta",
        image: "/picked-characters-and-wepaons/carlotta-wuwa-pic.avif",
        detailImage: "/picked-characters-and-wepaons/carlotta-wuwa-pic.avif",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Pistols",
        weaponName: "The Last Dance",
        role: "Showcase Pick",
        type: "Glacio",
        englishVoiceActor: "Jennifer English",
        japaneseVoiceActor: "Ueda Kana",
        weaponImage: "/picked-characters-and-wepaons/Weapon_The_Last_Dance_carlotta.jpeg",
      },
      {
        name: "Fluerdays",
        image: "/picked-characters-and-wepaons/cartethyia-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/cartethyia-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Sword",
        weaponName: "Defier's Thorn",
        role: "Showcase Pick",
        type: "Aero",
        englishVoiceActor: "Amanda Elizabeth Rischel",
        japaneseVoiceActor: "Asakawa Yu",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Defier's_Thorn.jpeg",
      },
      {
        name: "Chisa",
        image: "/picked-characters-and-wepaons/chisa-wuwa-pic.webp",
        detailImage: "/picked-characters-and-wepaons/chisa-wuwa-pic.webp",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Sword",
        weaponName: "Kumo Kiri",
        role: "Showcase Pick",
        type: "Havoc",
        englishVoiceActor: "Leader Looi",
        japaneseVoiceActor: "Kanemoto Hisako",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Kumo_Kiri_chisa.jpeg",
      },
      {
        name: "Ciaccona",
        image: "/picked-characters-and-wepaons/ciaccona-wuwa-pic.webp",
        detailImage: "/picked-characters-and-wepaons/ciaccona-wuwa-pic.webp",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Pistols",
        weaponName: "Woodland Aria",
        role: "Showcase Pick",
        type: "Aero",
        englishVoiceActor: "Rebecca Hanssen",
        japaneseVoiceActor: "Hasegawa Ikumi",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Woodland_Aria_ciaccona.jpeg",
      },
      {
        name: "Galbrena",
        image: "/picked-characters-and-wepaons/galbrena-wuwa-pic.webp",
        detailImage: "/picked-characters-and-wepaons/galbrena-wuwa-pic.webp",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Pistols",
        weaponName: "Lux & Umbra",
        role: "Showcase Pick",
        type: "Fusion",
        englishVoiceActor: "Devora Wilde; Leonie Schliesing (Angel / Young Galbrena)",
        japaneseVoiceActor: "Shoji Umeka",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Lux_&_Umbra.jpeg",
      },
      {
        name: "Hiyuki",
        image: "/picked-characters-and-wepaons/hiyuki-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/hiyuki-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Unknown",
        role: "Showcase Pick",
        type: "Glacio",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
        weaponImage: "/weapon-core.svg",
      },
      {
        name: "Iuno",
        image: "/picked-characters-and-wepaons/iuno-wuwa-pic.webp",
        detailImage: "/picked-characters-and-wepaons/iuno-wuwa-pic.webp",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Gauntlets",
        weaponName: "Moongazer's Sigil",
        role: "Showcase Pick",
        type: "Aero",
        englishVoiceActor: "Ella Boyes",
        japaneseVoiceActor: "Lynn",
        weaponImage: "/picked-characters-and-wepaons/weapon_Moongazer's_Sigil_iuno.jpeg",
      },
      {
        name: "Lupa",
        image: "/picked-characters-and-wepaons/lupa-wuwa-pic.avif",
        detailImage: "/picked-characters-and-wepaons/lupa-wuwa-pic.avif",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Broadblade",
        weaponName: "Wildfire Mark",
        role: "Showcase Pick",
        type: "Fusion",
        englishVoiceActor: "Kaja Chan",
        japaneseVoiceActor: "Takahashi Minami",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Wildfire_Mark_lupa.webp",
      },
      {
        name: "Phrolova",
        image: "/picked-characters-and-wepaons/phrolova-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/phrolova-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Rectifier",
        weaponName: "Lethean Elegy",
        role: "Showcase Pick",
        type: "Havoc",
        englishVoiceActor: "Rae Lim",
        japaneseVoiceActor: "Fujita Saki",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Lethean_Elegy_phrolova.webp",
      },
      {
        name: "Sigrika",
        image: "/picked-characters-and-wepaons/sigrika-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/sigrika-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Gauntlets",
        weaponName: "Solsworn Ciphers",
        role: "Showcase Pick",
        type: "Aero",
        englishVoiceActor: "Maya Lindh",
        japaneseVoiceActor: "Akasaki Chinatsu",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Solsworn_Ciphers_sigrika.jpeg",
      },
      {
        name: "Xiangli Yao",
        image: "/picked-characters-and-wepaons/xiangli-yao-wuwa-pic.jpg",
        detailImage: "/picked-characters-and-wepaons/xiangli-yao-wuwa-pic.jpg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Gauntlets",
        weaponName: "Verity's Handle",
        role: "Showcase Pick",
        type: "Electro",
        englishVoiceActor: "Shaun Mendum",
        japaneseVoiceActor: "Kobayashi Chiaki",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Verity's_Handle.webp",
      },
      {
        name: "Zani",
        image: "/picked-characters-and-wepaons/zani-wuwa-pic.jpeg",
        detailImage: "/picked-characters-and-wepaons/zani-wuwa-pic.jpeg",
        description: "Added from your Wuwa portrait collection as another showcase pick for the main page roster.",
        weapon: "Gauntlets",
        weaponName: "Blazing Justice",
        role: "Showcase Pick",
        type: "Spectro",
        englishVoiceActor: "Alexandra Metaxa",
        japaneseVoiceActor: "Ueda Hitomi",
        weaponImage: "/picked-characters-and-wepaons/Weapon_Blazing_Justice_zani.webp",
      },
    ],
  },
  {
    slug: "free-fire-max",
    name: "Free Fire",
    imgSrc: "/side-bar/Garena-logo.jpg",
    bannerSrc: "/side-bar/Garena-logo.jpg",
    uid: "FFM 71 440 298",
    favoriteCharacter: "Alok",
    favoriteCharacterDescription: "Reliable in quick squad pushes, mobility-heavy fights, and the kind of matches where tempo matters most.",
    about: "My quick-match profile for casual squad sessions, ranked pushes, and experimenting with aggressive loadouts.",
    status: "Heroic Rank",
    tagline: "Fast squad games, ranked sessions, and aggressive loadouts.",
    characters: [
      {
        name: "Kelly",
        image: "/picked-characters-and-wepaons/Kely-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/Kely-ff.jpg",
        imageAspectRatio: "1078 / 1118",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A classic speed pick for quick rotations, early positioning, and aggressive repositioning.",
        role: "Speedster",
        type: "Mobility",
        typeImage: "/element/kelly-logo.png",
        skillName: "Dash",
        skillType: "Passive",
        skillDescription: "Boosts sprinting speed, making Kelly useful for fast rotations, flanks, and quick escapes from bad fights.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Moco",
        image: "/picked-characters-and-wepaons/moco-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/moco-ff.jpg",
        imageAspectRatio: "1062 / 1070",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A smart tracking pick for marking enemies and giving the squad cleaner follow-up information.",
        role: "Tracker",
        type: "Intel",
        typeImage: "/element/moco-logo.png",
        skillName: "Hacker's Eye",
        skillType: "Passive",
        skillDescription: "Marks enemies after they are hit, giving the squad cleaner tracking and easier follow-up pressure.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Rin",
        image: "/picked-characters-and-wepaons/rin-ff.webp",
        detailImage: "/picked-characters-and-wepaons/rin-ff.webp",
        imageAspectRatio: "826 / 696",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A stylish favorite pick for faster match tempo and flexible squad compositions.",
        role: "Flex",
        type: "Tempo",
        typeImage: "/element/rin-logo.png",
        skillName: "Gale of Kunai",
        skillType: "Passive",
        skillDescription: "Summons kunai over time that can follow up on enemies or Gloo Walls you hit, adding extra pressure during pushes.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Suzy",
        image: "/picked-characters-and-wepaons/suzy-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/suzy-ff.jpg",
        imageAspectRatio: "16 / 9",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A reward-focused pick for active fights, aggressive eliminations, and keeping match momentum high.",
        role: "Bounty Hunter",
        type: "Aggressive",
        typeImage: "/element/suzy-logo.png",
        skillName: "Money Mark",
        skillType: "Passive",
        skillDescription: "Rewards aggressive eliminations by marking targets for bounty-style pressure and better match momentum.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Steffie",
        image: "/picked-characters-and-wepaons/Steffie-ff.webp",
        detailImage: "/picked-characters-and-wepaons/Steffie-ff.webp",
        imageAspectRatio: "829 / 1438",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A defensive utility pick for safer team fights, steadier holds, and clutch zone control.",
        role: "Defender",
        type: "Utility",
        typeImage: "/element/steffie-logo.png",
        skillName: "Painted Refuge",
        skillType: "Active",
        skillDescription: "Creates a protective graffiti zone that helps the team hold space, reduce incoming pressure, and reset safer.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Alok",
        image: "/picked-characters-and-wepaons/Alok-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/Alok-ff.jpg",
        imageAspectRatio: "1 / 1",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "My preferred utility pick for mobility-heavy matches and fast squad pressure.",
        role: "Support",
        type: "Healer",
        typeImage: "/element/alok-logo.png",
        skillName: "Drop the Beat",
        skillType: "Active",
        skillDescription: "Creates a support aura for movement and healing, making Alok strong for squad pushes and quick repositioning.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Dasha",
        image: "/picked-characters-and-wepaons/Dasha-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/Dasha-ff.jpg",
        imageAspectRatio: "168 / 300",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A fast, aggressive pick for close-range fights and smoother movement during chaotic pushes.",
        role: "Mobility",
        type: "Rusher",
        typeImage: "/element/dasha-logo.png",
        skillName: "Partying On",
        skillType: "Passive",
        skillDescription: "Improves control during messy fights by helping with recoil handling and reducing the punishment from falls.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Hayato",
        image: "/picked-characters-and-wepaons/Hayato-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/Hayato-ff.jpg",
        imageAspectRatio: "1 / 1",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A sharp duel-focused character for confident close-range fights and clutch pressure moments.",
        role: "Duelist",
        type: "Entry",
        typeImage: "/element/hayato-logo.png",
        skillName: "Bushido",
        skillType: "Passive",
        skillDescription: "Increases armor penetration as HP drops, making Hayato dangerous in clutch duels and low-health trades.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Iris",
        image: "/picked-characters-and-wepaons/Iris-ff.webp",
        detailImage: "/picked-characters-and-wepaons/Iris-ff.webp",
        imageAspectRatio: "4 / 3",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A utility-heavy pick for breaking defensive setups and keeping squad fights moving forward.",
        role: "Utility",
        type: "Rusher",
        typeImage: "/element/iris-logo.png",
        skillName: "Wall Brawl",
        skillType: "Active",
        skillDescription: "Counters Gloo Wall cover by marking nearby enemies and letting shots pressure targets behind the wall.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Caroline",
        image: "/picked-characters-and-wepaons/caroline-ff.jpg",
        detailImage: "/picked-characters-and-wepaons/caroline-ff.jpg",
        imageAspectRatio: "661 / 1024",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A close-range favorite for shotgun-heavy pushes and fast indoor fights.",
        role: "Shotgunner",
        type: "Close Range",
        typeImage: "/element/caroline-logo.png",
        skillName: "Agility",
        skillType: "Passive",
        skillDescription: "Increases movement speed while holding a shotgun, making Caroline fit fast close-range entries.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Sonia",
        image: "/picked-characters-and-wepaons/sonia-ff.webp",
        detailImage: "/picked-characters-and-wepaons/sonia-ff.webp",
        imageAspectRatio: "1407 / 2441",
        imagePosition: "center 18%",
        detailImagePosition: "center 12%",
        description: "A comeback-focused pick for risky engagements and turning tight fights back in your favor.",
        role: "Survivor",
        type: "Clutch",
        typeImage: "/element/sonia-logo.png",
        skillName: "Nano Lifeshield",
        skillType: "Passive",
        skillDescription: "Gives a last-second survival window after fatal damage, built for risky fights and comeback moments.",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
    ],
  },
  {
    slug: "bgmi",
    name: "PUBG",
    imgSrc: "/side-bar/Bgmi.jpg",
    bannerSrc: "/side-bar/Bgmi.jpg",
    uid: "PUBG 5538 99417",
    favoriteCharacter: "Victor",
    favoriteCharacterDescription: "A practical pick that matches how I approach the profile: efficient drills, control, and consistency under pressure.",
    about: "Competitive account tuned for classic matches, recoil control practice, and coordinated drop routes with friends.",
    status: "Ace Master",
    tagline: "Competitive routes, recoil discipline, and ranked grind.",
    characters: [
      {
        name: "Victor",
        image: "/picked-characters-and-wepaons/victor-bgmi.jpg",
        detailImage: "/picked-characters-and-wepaons/victor-bgmi.jpg",
        imageAspectRatio: "800 / 1065",
        imagePosition: "center 16%",
        detailImagePosition: "center 10%",
        description: "A practical favorite that matches how I approach the account: controlled, consistent, and efficient.",
        role: "Rusher",
        type: "Close Range",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Sara",
        image: "/picked-characters-and-wepaons/sara-bgmi.jpg",
        detailImage: "/picked-characters-and-wepaons/sara-bgmi.jpg",
        imageAspectRatio: "1920 / 3414",
        imagePosition: "center 14%",
        detailImagePosition: "center 8%",
        description: "A steady choice when I want endurance-focused sessions and longer ranked grinds.",
        role: "Sniper",
        type: "Long Range",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
      {
        name: "Anna",
        image: "/picked-characters-and-wepaons/Anna-bgmi.jpg",
        detailImage: "/picked-characters-and-wepaons/Anna-bgmi.jpg",
        imageAspectRatio: "1 / 1",
        imagePosition: "center",
        detailImagePosition: "center",
        description: "Useful for smoother healing tempo and stable team-oriented match flow.",
        role: "Support",
        type: "Team Utility",
        englishVoiceActor: "Not listed",
        japaneseVoiceActor: "Not listed",
      },
    ],
  },
  {
    slug: "arknight-endfield",
    name: "Arknights: Endfield",
    imgSrc: "/side-bar/Arknight-Endfield.jpg",
    bannerSrc: "/side-bar/Arknight-Endfield.jpg",
    uid: "AEF Preview Build",
    favoriteCharacter: "Perlica",
    favoriteCharacterDescription: "A standout from the worldbuilding and reveal material that makes the whole project feel worth tracking closely.",
    about: "A watchlist profile for one of my most anticipated sci-fi worlds, tracked for updates, reveals, and team ideas.",
    status: "Following Closely",
    tagline: "A future-facing profile built around anticipation and worldbuilding.",
    characters: [
      {
        name: "Perlica",
        image: "/picked-characters-and-wepaons/Perlica-ark.webp",
        detailImage: "/picked-characters-and-wepaons/Perlica-ark.webp",
        imageAspectRatio: "392 / 448",
        imagePosition: "center 12%",
        detailImagePosition: "center 8%",
        description: "Perlica is the Arknights: Endfield character I want to keep at the center of this page. She has that calm, composed companion energy that fits the game's industrial frontier setting really well. Her design feels clean and futuristic without looking too loud, and she gives the roster a steady support presence instead of just another combat-focused pick. For this profile, she works as the face of the Endfield section: reliable, polished, and closely tied to the tone of the world.",
        role: "Support",
        type: "Logistics / Support",
        englishVoiceActor: "Jane Jackson",
        japaneseVoiceActor: "Shion Wakayama",
      },
      {
        name: "Endministrator",
        image: "/picked-characters-and-wepaons/endmin-ark.png",
        detailImage: "/picked-characters-and-wepaons/endmin-ark.png",
        imageAspectRatio: "894 / 1198",
        imagePosition: "center 10%",
        detailImagePosition: "center 6%",
        description: "The Endministrator fits this page as the main tactical lead and player-side identity for Arknights: Endfield. This character represents the command role more than a simple frontline unit, so the profile works better when it focuses on presence, leadership, and connection to the world instead of weapon stats. I like keeping this pick here because it makes the Endfield page feel personal: not just a roster list, but the character perspective that anchors the whole game profile.",
        role: "Tactical Lead",
        type: "Command / Operations",
      },
    ],
  },

];

export function getGameBySlug(slug: string) {
  return gameData.find((game) => game.slug === slug);
}
